[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_lend_borrow = "7x1VvJoMWUJobpk1TkzT4Yb8248sSK1XmA7s2CZDUoA6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mac/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
